services:
  mc:
    container_name: neoforge-1.21.1-dark-hours
    image: itzg/minecraft-server
    environment:
      TYPE: AUTO_CURSEFORGE
      VERSION: "1.21.1"
      EULA: true

      INIT_MEMORY: 6G
      MEMORY: 12G
      USE_AIKAR_FLAGS: true

      PVP: true
      ALLOW_FLIGHT: true
      ENABLE_COMMAND_BLOCK: true
      DIFFICULTY: "hard"
      MOTD: "Le serveur de tes rêves"

      CF_API_KEY: ${CF_API_KEY}
      CF_SLUG: "dark-hours"
      CF_FILE_ID: "6973150"
    networks:
      - proxy
    ports:
      - "25565:25565"
      - "24454:24454/udp"
      - "8080:8080"
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
networks:
  proxy:
    external: true
    name: proxy-network
